export enum Genres {
  business = 'Бизнес-книги',
  detective = 'Детективы',
  children = 'Детские книги',
  foreign = 'Зарубежная литература',
  history = 'История',
  classic = 'Классическая литература',
  psychology = 'Книги по психологии',
  computers = 'Компьютерная литература',
  culture = 'Культура и искусство',
  science = 'Наука и образование',
  publicistic = 'Публицистическая литература',
  references = 'Справочники',
  scifi = 'Фантастика',
  humor = 'Юмористическая литература',
}
